-- CALLED IT! — row level security
-- Defense in depth: RLS policies decide WHICH rows, column-level grants decide
-- WHICH columns clients may write. The service role bypasses RLS, so
-- "service-role only" simply means no policy/grant for anon/authenticated.

alter table public.sports         enable row level security;
alter table public.competitions   enable row level security;
alter table public.teams          enable row level security;
alter table public.fixtures       enable row level security;
alter table public.profiles       enable row level security;
alter table public.predictions    enable row level security;
alter table public.leagues        enable row level security;
alter table public.league_members enable row level security;
alter table public.referrals      enable row level security;
alter table public.platform_votes enable row level security;
alter table public.sync_runs      enable row level security;

-- Baseline: no client writes anywhere; grant back narrowly below.
revoke insert, update, delete on all tables in schema public from anon, authenticated;

-- Catalog tables: public read, cron-only (service role) writes.
create policy "sports are public"
  on public.sports for select
  to anon, authenticated
  using (true);

create policy "competitions are public"
  on public.competitions for select
  to anon, authenticated
  using (true);

create policy "teams are public"
  on public.teams for select
  to anon, authenticated
  using (true);

create policy "fixtures are public"
  on public.fixtures for select
  to anon, authenticated
  using (true);

-- Profiles: readable by everyone (leaderboards, share pages). Clients may
-- update only their own row, and only display_name/avatar_seed — points,
-- streak, flex_tokens and pass_tier stay service-role-only via column grants.
create policy "profiles are public"
  on public.profiles for select
  to anon, authenticated
  using (true);

create policy "users update own profile"
  on public.profiles for update
  to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

grant update (display_name, avatar_seed) on public.profiles to authenticated;

-- Predictions: your own always; rivals' picks only after kickoff (no pick
-- copying). Writes require an open fixture (also enforced by trigger), and
-- column grants keep points_awarded/locked_at out of client hands.
create policy "read own or post-kickoff predictions"
  on public.predictions for select
  to authenticated
  using (
    user_id = auth.uid()
    or exists (
      select 1 from public.fixtures f
      where f.id = fixture_id and f.kickoff_utc <= now()
    )
  );

create policy "insert own prediction while open"
  on public.predictions for insert
  to authenticated
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.fixtures f
      where f.id = fixture_id
        and f.kickoff_utc > now()
        and f.status in ('scheduled', 'timed')
        and f.home_id is not null
        and f.away_id is not null
    )
  );

create policy "update own prediction while open"
  on public.predictions for update
  to authenticated
  using (user_id = auth.uid())
  with check (
    user_id = auth.uid()
    and exists (
      select 1 from public.fixtures f
      where f.id = fixture_id
        and f.kickoff_utc > now()
        and f.status in ('scheduled', 'timed')
        and f.home_id is not null
        and f.away_id is not null
    )
  );

create policy "delete own prediction while open"
  on public.predictions for delete
  to authenticated
  using (
    user_id = auth.uid()
    and exists (
      select 1 from public.fixtures f
      where f.id = fixture_id and f.kickoff_utc > now()
    )
  );

grant insert (user_id, fixture_id, home_pick, away_pick) on public.predictions to authenticated;
grant update (home_pick, away_pick) on public.predictions to authenticated;
grant delete on public.predictions to authenticated;

-- Leagues: visible only to owner/members (private.is_league_member is
-- SECURITY DEFINER, so no policy recursion and no enumeration — joining
-- happens exclusively through join_league_by_code). Pods are created by the
-- service role, hence is_pod = false on client inserts; invite_code is
-- server-generated by default and not client-writable.
create policy "members read their leagues"
  on public.leagues for select
  to authenticated
  using (owner_id = auth.uid() or private.is_league_member(id));

create policy "users create own leagues"
  on public.leagues for insert
  to authenticated
  with check (owner_id = auth.uid() and is_pod = false);

create policy "owner updates league"
  on public.leagues for update
  to authenticated
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());

create policy "owner deletes league"
  on public.leagues for delete
  to authenticated
  using (owner_id = auth.uid());

grant insert (name, owner_id) on public.leagues to authenticated;
grant update (name) on public.leagues to authenticated;
grant delete on public.leagues to authenticated;

-- League members: no direct inserts (owner trigger + join RPC only).
create policy "members read co-members"
  on public.league_members for select
  to authenticated
  using (user_id = auth.uid() or private.is_league_member(league_id));

create policy "users leave leagues"
  on public.league_members for delete
  to authenticated
  using (user_id = auth.uid());

create policy "owner removes members"
  on public.league_members for delete
  to authenticated
  using (
    exists (
      select 1 from public.leagues l
      where l.id = league_id and l.owner_id = auth.uid()
    )
  );

grant delete on public.league_members to authenticated;

-- Referrals: readable by either side; written only via claim_referral.
create policy "read own referrals"
  on public.referrals for select
  to authenticated
  using (auth.uid() in (referrer_id, joined_id));

-- Platform votes: one vote per user per platform (unique constraint).
create policy "votes are readable"
  on public.platform_votes for select
  to authenticated
  using (true);

create policy "users cast own vote"
  on public.platform_votes for insert
  to authenticated
  with check (user_id = auth.uid());

create policy "users retract own vote"
  on public.platform_votes for delete
  to authenticated
  using (user_id = auth.uid());

grant insert (platform, user_id) on public.platform_votes to authenticated;
grant delete on public.platform_votes to authenticated;

-- sync_runs: no policies — service role only.
